import { useState, useEffect } from 'react';
import {
  Box, TextField, Button, MenuItem, Alert, Typography, Grid,
  Breadcrumbs, Link, Paper, Divider, Chip,
} from '@mui/material';
import {
  ArrowBack as ArrowBackIcon,
  NavigateNext as NavigateNextIcon,
  QrCode as QrCodeIcon,
  Inventory as InventoryIcon,
  Add as AddIcon,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import PortalLayout from '../../../components/layout/PortalLayout';
import Section from '../../../components/enterprise/Section';
import LoadingSpinner from '../../../components/common/LoadingSpinner';
import QrPreviewDialog from '../../../components/common/QrPreviewDialog';
import useAuth from '../../../hooks/useAuth';
import binService from '../../../services/binService';
import masterService from '../../../services/masterService';

// ─── Capacity units ────────────────────────────────────────────────────────

const CAPACITY_UNITS = ['L', 'kg', 'g', 'mL', 'units'];

// ─── Form field validation ─────────────────────────────────────────────────

function getFieldError(form, field) {
  if (!form._touched?.[field]) return null;
  switch (field) {
    case 'binTypeId':
      if (!form.binTypeId) return 'Bin Type is required';
      return null;
    case 'binCategoryId':
      if (!form.binCategoryId) return 'Bin Category is required';
      return null;
    case 'capacity':
      if (!form.capacity || parseFloat(form.capacity) <= 0) return 'Capacity must be greater than zero';
      return null;
    case 'capacityUnit':
      if (!form.capacityUnit.trim()) return 'Unit is required';
      return null;
    default:
      return null;
  }
}

// ─── Main Component ────────────────────────────────────────────────────────

export default function BinRegister() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const [form, setForm] = useState({
    binTypeId: '',
    binCategoryId: '',
    capacity: '',
    capacityUnit: 'L',
    _touched: {},
  });
  const [binTypes, setBinTypes] = useState([]);
  const [binCategories, setBinCategories] = useState([]);
  const [error, setError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [createdBin, setCreatedBin] = useState(null);

  // Load dropdowns
  useEffect(() => {
    masterService.getBinTypes().then(r => setBinTypes(r.data?.data || [])).catch(() => {});
    masterService.getBinCategories().then(r => setBinCategories(r.data?.data || [])).catch(() => {});
  }, []);

  // Field update with touch tracking
  const handleChange = (field) => (e) => {
    setForm(prev => ({
      ...prev,
      [field]: e.target.value,
      _touched: { ...prev._touched, [field]: true },
    }));
  };

  // Is form valid (Bin Number is auto-generated by backend)
  const isValid =
    form.binTypeId !== '' &&
    form.binCategoryId !== '' &&
    parseFloat(form.capacity) > 0 &&
    form.capacityUnit.trim().length > 0;

  // Submit handler
  const handleSubmit = async (e) => {
    e?.preventDefault();
    setError(null);

    // Touch all fields to show validation
    setForm(prev => ({
      ...prev,
      _touched: {
        binTypeId: true,
        binCategoryId: true,
        capacity: true,
        capacityUnit: true,
      },
    }));

    if (!isValid) return;

    setSubmitting(true);
    try {
      const res = await binService.registerBin({
        binTypeId: parseInt(form.binTypeId, 10),
        binCategoryId: parseInt(form.binCategoryId, 10),
        capacity: parseFloat(form.capacity),
        capacityUnit: form.capacityUnit.trim(),
      });
      setCreatedBin(res.data?.data);
    } catch (err) {
      const msg = err.response?.data?.error?.message || 'Failed to create bin';
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  };

  // After QR dialog closed
  const handleQrClose = () => {
    setCreatedBin(null);
    navigate('/admin/bins');
  };

  const fieldError = (field) => getFieldError(form, field);

  return (
    <PortalLayout user={user} onLogout={logout}>
      <Box>
        {/* Breadcrumb */}
        <Breadcrumbs
          separator={<NavigateNextIcon sx={{ fontSize: 11 }} />}
          sx={{ mb: 0.75 }}
        >
          <Link
            underline="hover"
            color="inherit"
            onClick={() => navigate('/admin/bins')}
            sx={{ cursor: 'pointer', fontSize: '0.68rem', fontWeight: 500 }}
          >
            Masters
          </Link>
          <Typography
            variant="caption"
            sx={{ fontSize: '0.68rem', color: 'primary.main', fontWeight: 600 }}
          >
            Create Bin
          </Typography>
        </Breadcrumbs>

        {/* Header */}
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            mb: 1.5,
            flexWrap: 'wrap',
            gap: 1,
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
            <Typography sx={{ fontWeight: 700, fontSize: '0.95rem' }}>
              Create Bin
            </Typography>
            <Typography
              variant="caption"
              color="text.secondary"
              sx={{ fontSize: '0.7rem' }}
            >
              Register a new pharmaceutical container into the system
            </Typography>
          </Box>
          <Button
            size="small"
            variant="outlined"
            startIcon={<ArrowBackIcon sx={{ fontSize: 15 }} />}
            onClick={() => navigate('/admin/bins')}
            sx={{ fontSize: '0.68rem', py: 0.3 }}
          >
            Back to Bin Master
          </Button>
        </Box>

        {/* Error alert */}
        {error && (
          <Alert
            severity="error"
            sx={{ mb: 1.5, fontSize: '0.72rem' }}
            onClose={() => setError(null)}
          >
            {error}
          </Alert>
        )}

        <Box component="form" onSubmit={handleSubmit} noValidate>
          {/* Basic Information */}
          <Section title="Basic Information">
            <Grid container spacing={1.5}>
              <Grid item xs={12} sm={6}>
                <TextField
                  label="Bin Type"
                  value={form.binTypeId}
                  onChange={handleChange('binTypeId')}
                  required
                  fullWidth
                  size="small"
                  select
                  error={Boolean(fieldError('binTypeId'))}
                  helperText={fieldError('binTypeId')}
                  sx={{ '& .MuiInputBase-root': { fontSize: '0.72rem' } }}
                >
                  {binTypes.map(t => (
                    <MenuItem key={t.Bin_Type_ID} value={t.Bin_Type_ID} sx={{ fontSize: '0.72rem' }}>
                      {t.Type_Name}
                    </MenuItem>
                  ))}
                </TextField>
              </Grid>
              <Grid item xs={12} sm={6}>
                <TextField
                  label="Bin Category"
                  value={form.binCategoryId}
                  onChange={handleChange('binCategoryId')}
                  required
                  fullWidth
                  size="small"
                  select
                  error={Boolean(fieldError('binCategoryId'))}
                  helperText={fieldError('binCategoryId')}
                  sx={{ '& .MuiInputBase-root': { fontSize: '0.72rem' } }}
                >
                  {binCategories.map(c => (
                    <MenuItem key={c.Bin_Category_ID} value={c.Bin_Category_ID} sx={{ fontSize: '0.72rem' }}>
                      {c.Category_Name}
                    </MenuItem>
                  ))}
                </TextField>
              </Grid>
            </Grid>
          </Section>

          {/* Capacity */}
          <Section title="Capacity">
            <Grid container spacing={1.5}>
              <Grid item xs={12} sm={4}>
                <TextField
                  label="Capacity"
                  type="number"
                  value={form.capacity}
                  onChange={handleChange('capacity')}
                  required
                  fullWidth
                  size="small"
                  error={Boolean(fieldError('capacity'))}
                  helperText={fieldError('capacity')}
                  inputProps={{ min: 0.001, step: 0.001 }}
                  sx={{ '& .MuiInputBase-root': { fontSize: '0.72rem' } }}
                />
              </Grid>
              <Grid item xs={12} sm={3}>
                <TextField
                  label="Unit"
                  value={form.capacityUnit}
                  onChange={handleChange('capacityUnit')}
                  required
                  fullWidth
                  size="small"
                  select
                  error={Boolean(fieldError('capacityUnit'))}
                  helperText={fieldError('capacityUnit')}
                  sx={{ '& .MuiInputBase-root': { fontSize: '0.72rem' } }}
                >
                  {CAPACITY_UNITS.map(u => (
                    <MenuItem key={u} value={u} sx={{ fontSize: '0.72rem' }}>{u}</MenuItem>
                  ))}
                </TextField>
              </Grid>
            </Grid>
          </Section>

          {/* Registration preview (all system-managed fields) */}
          <Paper
            variant="outlined"
            sx={{
              p: 1.5,
              mb: 2,
              bgcolor: '#F8FAFD',
              display: 'flex',
              alignItems: 'center',
              gap: 1.5,
              flexWrap: 'wrap',
            }}
          >
            <Typography
              variant="caption"
              color="text.secondary"
              sx={{ fontSize: '0.62rem', fontWeight: 600, letterSpacing: '0.05em' }}
            >
              SYSTEM GENERATED
            </Typography>
            <Divider orientation="vertical" flexItem />
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.4 }}>
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.6rem' }}>
                Bin Number
              </Typography>
              <Chip label="Auto" size="small" sx={{ height: 18, fontSize: '0.55rem', bgcolor: '#E3F0FF', color: '#1565C0' }} />
            </Box>
            <Divider orientation="vertical" flexItem />
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.4 }}>
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.6rem' }}>
                Bin ID
              </Typography>
              <Chip label="Auto" size="small" sx={{ height: 18, fontSize: '0.55rem', bgcolor: '#E3F0FF', color: '#1565C0' }} />
            </Box>
            <Divider orientation="vertical" flexItem />
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.4 }}>
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.6rem' }}>
                Status
              </Typography>
              <Chip
                label="Available"
                size="small"
                sx={{ height: 18, fontSize: '0.58rem', fontWeight: 600, bgcolor: '#E8F5E9', color: '#2E7D32' }}
              />
            </Box>
            <Divider orientation="vertical" flexItem />
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.4 }}>
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.6rem' }}>
                Cycle Count
              </Typography>
              <Typography variant="caption" sx={{ fontWeight: 600, fontSize: '0.65rem' }}>0</Typography>
            </Box>
            <Divider orientation="vertical" flexItem />
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.4 }}>
              <QrCodeIcon sx={{ fontSize: 14, color: 'text.disabled' }} />
              <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.6rem' }}>
                QR generated automatically
              </Typography>
            </Box>
          </Paper>

          {/* Actions */}
          <Box sx={{ display: 'flex', gap: 1, justifyContent: 'flex-end' }}>
            <Button
              variant="outlined"
              size="small"
              onClick={() => navigate('/admin/bins')}
              sx={{ fontSize: '0.68rem', py: 0.5 }}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="contained"
              size="small"
              disabled={!isValid || submitting}
              startIcon={submitting ? undefined : <AddIcon sx={{ fontSize: 16 }} />}
              sx={{ fontSize: '0.68rem', py: 0.5, minWidth: 130 }}
            >
              {submitting ? 'Creating...' : 'Create Bin'}
            </Button>
          </Box>
        </Box>

        {/* Loading overlay */}
        {submitting && <LoadingSpinner fullScreen />}

        {/* Success QR dialog */}
        <QrPreviewDialog
          open={!!createdBin}
          bin={createdBin}
          onClose={handleQrClose}
        />
      </Box>
    </PortalLayout>
  );
}